#### Playbook Pre-Upgrade
---
- name: Update Crypto Policy to Legacy
  hosts: all
  become: yes
  tasks:

  - name: Show current crypto policy
    ansible.builtin.command:
      cmd: update-crypto-policies --show
    register: current_policy

  - name: Display current crypto policy
    ansible.builtin.debug:
      msg: "Current crypto policy: {{ current_policy.stdout }}"

  - name: Set crypto policy to LEGACY
    ansible.builtin.command:
      cmd: update-crypto-policies --set LEGACY

  - name: Show updated crypto policy
    ansible.builtin.command:
      cmd: update-crypto-policies --show
    register: updated_policy

  - name: Display updated crypto policy
    ansible.builtin.debug:
      msg: "Updated crypto policy: {{ updated_policy.stdout }}"
